additionalProperties:
  supportsES6: true
  npmName: docker-api-ts
  npmVersion: 1.0.0
  # apiPackage: api
  # modelPackage: models
  # withSeparateModelsAndApi: true
  stringEnums: true
  withNodeImports: false